                         CLS
                         PRINT "what was the bullets mass?"
                         INPUT mb
                         PRINT "what was the targets mass?"
                         INPUT mt
                         PRINT "what was the length of the target?"
                         INPUT L
                         PRINT "what time was required for the target to pass through the beam of light?"
                         INPUT T
                         vt = L / T
                         vb = (mt + mb) * vt / mb
                         PRINT "the bullets velocity = "; vb; " cm/s"
                         













                         
            

