' *** Marty Thornley   ***
' *** April 5,1993     ***
' *** Period 3         ***
' *** Another madlib   ***
CLS
PRINT "Type a ..."
INPUT "    Expression"; ex$
INPUT "    Verb"; v$
INPUT "    Verb"; ve$
INPUT "    Verb"; ver$
PRINT "    get used to this there's lots o' verbsssssssss"
INPUT "    velb, prease"; verb$
INPUT "    ural play oun nay "; pln$
INPUT "    N O U N"; N$
INPUT "    giwe me a wery good werb"; va$
INPUT "    please a verb to be given me, to me, right now by you"; vb$
INPUT "    Hey kid, what's your name"; nme$
INPUT "    GIVEMEANOUNNOWPLEASEYESYOURIGHTNOWANOUNNOUNNOUN"; WRD$
INPUT "    aVerbVerbVerb A Verb IS THE WORD V-V-VerbVerbVerb"; vbc$
INPUT "    nnnooouuunnn"; noun$
INPUT "    not a verb, not an adjective, not anything but a noun"; nou$
INPUT "    g-give m-me a-a v-verb"; verver$
INPUT "    that thing that's like an adjective but spelled adverb"; adv$
PRINT "     the noun left so I needs somethings to take its place."
INPUT "       (that's a pronoun for yous whos ditn't understands mes"; pr$
LPRINT "Sayin', ` "; ex$; " 'is not the words i want to hear from you"
LPRINT "It's not that I "; v$; " you not to "; ve$; " but if you only "; ver$
LPRINT "how easy it would be to show me how you "; verb$;
LPRINT "more than "; pln$; " is all you have to do to make "; ns$; " real"
LPRINT "then you wouldn't have to say that you "; va$; " me"
LPRINT "'cause I'd already "; vb$
LPRINT "what would you do if "; nme$; "'s heart was torn in two?"
LPRINT "more than words to show you feel that your love for me is real "
LPRINT "what would you say if I took those "; WRD$; "s away"
LPRINT "then you couldn't make "; WRD$; "s new just by sayin' "
LPRINT "                                     "; ex$
LPRINT "Now that I've tried to talk to you and make you understand"
LPRINT "all that you have to do is "; vbc$; " your "; noun$
LPRINT "                                 and just reach out your "; nou$
LPRINT "and "; verver$; "me, hold me "; adv$; ",don't ever let me go "
LPRINT "more than words is all "; pr$; "ever needed you to show "
LPRINT "then you wouldn't have to say that you love "; nme$
LPRINT "                 'cause I'd already know."
END

